name: TestRpc
fileGroups: [
  Auth,
  Otp,
  Sms,
  Types,
]

configs:
  Debug: debug
  Release: release

schemes:
  TestRpc:
    build:
      targets:
        Auth: All
        Auth: [run, analyze, test, profile]
        Otp: All
        Otp: [run, analyze, test, profile]
        Sms: All
        Sms: [run, analyze, test, profile]
        Types: All
        Types: [run, analyze, test, profile]
    run:
      config: Debug
    archive:
      config: Release
    test:
      config: Debug


  Auth:
    build:
      targets:
        Auth: [run, analyze, test, profile]
    run:
      config: Debug
    archive:
      config: Release
    test:
      config: Debug

  Otp:
    build:
      targets:
        Otp: [run, analyze, test, profile]
    run:
      config: Debug
    archive:
      config: Release
    test:
      config: Debug

  Sms:
    build:
      targets:
        Sms: [run, analyze, test, profile]
    run:
      config: Debug
    archive:
      config: Release
    test:
      config: Debug

  Types:
    build:
      targets:
        Types: [run, analyze, test, profile]
    run:
      config: Debug
    archive:
      config: Release
    test:
      config: Debug


targets:
  Auth:
    type: framework
    platform: iOS
    deploymentTarget: "11.0"
    sources:
      - path: Auth/Sources
        buildPhase: sources
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: "com.suryadigital.leoSwiftRPCExample.auth"
        INFOPLIST_FILE: Auth/Info.plist

  Otp:
    type: framework
    platform: iOS
    deploymentTarget: "11.0"
    sources:
      - path: Otp/Sources
        buildPhase: sources
    dependencies:
      - target: Types
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: "com.suryadigital.leoSwiftRPCExample.otp"
        INFOPLIST_FILE: Otp/Info.plist

  Sms:
    type: framework
    platform: iOS
    deploymentTarget: "11.0"
    sources:
      - path: Sms/Sources
        buildPhase: sources
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: "com.suryadigital.leoSwiftRPCExample.sms"
        INFOPLIST_FILE: Sms/Info.plist

  Types:
    type: framework
    platform: iOS
    deploymentTarget: "11.0"
    sources:
      - path: Types/Sources
        buildPhase: sources
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: "com.suryadigital.leoSwiftRPCExample.types"
        INFOPLIST_FILE: Types/Info.plist

